#!/usr/bin/env bash
set -euo pipefail

rm -rf build dist

# Generated by cargo-xwin in the image, together with its CMake toolchain and
# LLVM tool aliases. Runtime builds do not mutate the root-owned xwin cache.
# shellcheck disable=SC1091
source /opt/rayneo-xwin-env.sh

cmake -S . -B build -G Ninja \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_TOOLCHAIN_FILE="${CMAKE_TOOLCHAIN_FILE_x86_64_pc_windows_msvc}" \
    -DRAYNEO_BUILD_OPENVR_DRIVER=OFF \
    -DRAYNEO_BUILD_EXAMPLES=OFF \
    -DLIBUSB_INCLUDE_DIR=/opt/libusb/include \
    -DLIBUSB_LIBRARY=/opt/libusb/VS2022/MS64/dll/libusb-1.0.lib

cmake --build build --target RayNeoSDK

PKG=dist/RayNeoSDK-${SDK_VERSION}-win64-msvc
mkdir -p "${PKG}/include" "${PKG}/bin" "${PKG}/lib"
cp include/rayneo_api.h "${PKG}/include/"
cp build/RayNeoSDK.dll "${PKG}/bin/"
cp build/RayNeoSDK.lib "${PKG}/lib/"
cp /opt/libusb/VS2022/MS64/dll/libusb-1.0.dll "${PKG}/bin/"
cp LICENSE "${PKG}/LICENSE"
cp docker/LICENSE-libusb.txt "${PKG}/LICENSE-libusb.txt"
cp docker/THIRD_PARTY_NOTICES.txt "${PKG}/THIRD_PARTY_NOTICES.txt"

tar -C dist -czf "${PKG}.tar.gz" "RayNeoSDK-${SDK_VERSION}-win64-msvc"
